### ISSUE TITLE
 I can't understand

### ISSUE THREAD

**Issue by rgnugc** [seia-soto/freeflight-interpark#1]
Hello, I can't understand 페이지에서 파일명이 zip으로 끝나는 확장 프로그램을 다운로드받고 압축을 풀어 창에 드래그하여 설치합니다. after pulling the project and installing the dependencies. the server responded with a status of 404 () 릴리즈

**Comment by seia-soto** [comment]
It seems you just encountered or accessed from invalid website. I'm closing it as invalid.
